" ------------------------------------------------------------------------------
" Options
" ------------------------------------------------------------------------------

let g:netrw_home = $XDG_DATA_HOME."/vim"

syntax on
filetype plugin indent on
set autoread
set hidden
set number
set relativenumber
set numberwidth=2
set cursorline
" set autoindent " Minimal automatic indenting for any filetype.
set backspace=indent,eol,start " Intuitive backspace behavior.

set nolist
set listchars=space:·,tab:>-,trail:·,nbsp:+,eol:↵
set fillchars+=eob:\

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

set hlsearch
set incsearch
set ignorecase
set smartcase

set wrap
set whichwrap+=<,>,[,]
set virtualedit=block
set scrolloff=10
set sidescrolloff=8
set laststatus=2
set ttimeoutlen=20
set timeoutlen=400
set path+=**
set wildignore+=*/node_modules/*
set wildmenu
set wildmode=longest:full,full
set synmaxcol=400
set signcolumn=auto
set foldcolumn=1
set foldlevelstart=30

set smoothscroll
set splitkeep=screen
set jumpoptions=stack

set linebreak
set breakindent
set mouse=a
set splitright splitbelow

" set lazyredraw
set termguicolors

set undodir=$XDG_DATA_HOME/vim/undo//
set undofile
set undolevels=1500

set viminfofile=$XDG_DATA_HOME/vim/viminfo

call mkdir($XDG_DATA_HOME.'/vim/undo', 'p')

" % jumps across if/else/endif, HTML tags
packadd! matchit

" Use a line cursor within insert mode and a block cursor everywhere else.
" Reference chart of values:
"   Ps = 0  -> blinking block.
"   Ps = 1  -> blinking block (default).
"   Ps = 2  -> steady block.
"   Ps = 3  -> blinking underline.
"   Ps = 4  -> steady underline.
"   Ps = 5  -> blinking bar (xterm).
"   Ps = 6  -> steady bar (xterm).
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
let &t_te .= "\e[2 q"

" ------------------------------------------------------------------------------
" Netrw
" ------------------------------------------------------------------------------

let g:netrw_banner=0
let g:netrw_altv=1
let g:netrw_list_hide = "^\./$"
let g:netrw_hide=1

" augroup netrw_mapping
"     autocmd!
"     autocmd filetype netrw nmap <buffer> <silent> H -
"     autocmd filetype netrw nmap <buffer> <silent> L <CR>
" augroup END

" ------------------------------------------------------------------------------
" Key mappings
" ------------------------------------------------------------------------------

let mapleader = " "

nnoremap <silent> Q :call KillBufferOrCloseWindow()<CR>

" <Esc> clears search highlight
nnoremap <silent> <Esc> :nohlsearch<CR>

" Move selected lines up/down (keeps selection)
vnoremap <silent> K :move '<-2<CR>gv=gv
vnoremap <silent> J :move '>+1<CR>gv=gv

" Keep cursor centered while scrolling/searching
nnoremap <silent> <C-d> <C-d>zz
nnoremap <silent> <C-u> <C-u>zz
nnoremap <silent> n nzzzv
nnoremap <silent> N Nzzzv

" Keep cursor in place while joining lines
nnoremap <silent> J mzJ`z

" Y behaves like C and D
nnoremap Y y$

" Paste over without losing the register
xnoremap p "_dP

" Delete to the black hole register (leader+d)
nnoremap <silent> <leader>d "_d
vnoremap <silent> <leader>d "_d

" System clipboard: <space>y/Y to copy, <space>p/P to paste
" (plain y/p use vim's internal registers)
nnoremap <silent> <leader>y "+y
vnoremap <silent> <leader>y "+y
nnoremap <silent> <leader>Y "+Y
vnoremap <silent> <leader>Y "+Y
nnoremap <silent> <leader>p "+p
vnoremap <silent> <leader>p "+p
nnoremap <silent> <leader>P "+P
vnoremap <silent> <leader>P "+P

" Alt+h/l buffer switching, Alt+j/k quickfix navigation
nnoremap <silent> <M-h> :bprevious<CR>
nnoremap <silent> <M-l> :bnext<CR>
nnoremap <silent> <M-j> :cnext<CR>
nnoremap <silent> <M-k> :cprev<CR>

" Replace word under cursor (Ctrl-S)
nnoremap <C-s> :%s/<C-r><C-w>/<C-r><C-w>/gIc<Left><Left><Left><Left>
vnoremap <C-s> :s///gIc<Left><Left><Left><Left><Left>

" Toggle invisible characters
nnoremap <silent> <leader>tl :set list!<CR>

" Make current file executable
nnoremap <silent> <leader>x :!chmod +x %<CR>

" Yank the whole file to the system clipboard
nnoremap <silent> <leader>[ :%yank +<CR>

" Disable arrow keys (forces hjkl navigation)
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
vnoremap <Up> <Nop>
vnoremap <Down> <Nop>
vnoremap <Left> <Nop>
vnoremap <Right> <Nop>

" ------------------------------------------------------------------------------
" Autocmds
" ------------------------------------------------------------------------------

augroup number_toggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

augroup text_filetype_specific_config
  autocmd!
  autocmd FileType text,markdown,org,gitcommit setlocal list
  autocmd FileType text,markdown,org,gitcommit setlocal listchars+=eol:↲
  autocmd FileType text,markdown,org,gitcommit setlocal spell
  autocmd FileType text,markdown,org,gitcommit setlocal spelllang=en_us,en_gb
augroup END

augroup code_filetype_specific_tab_config
  autocmd!
  autocmd FileType lua,yaml,json,vim setlocal tabstop=2 softtabstop=2 shiftwidth=2
augroup END

" Highlight the region just yanked/deleted (fades out)
let s:yank_hl_id = 0
function! s:yank_clear(...) abort
  if s:yank_hl_id
    silent! call matchdelete(s:yank_hl_id)
    let s:yank_hl_id = 0
  endif
endfunction
function! s:highlight_yank() abort
  if v:event.operator !~# '^[yd]$'
    return
  endif
  call s:yank_clear()
  let l:start = getpos("'[")
  let l:end = getpos("']")
  let l:pos = []
  if v:event.regtype ==# 'V'
    call extend(l:pos, range(l:start[1], l:end[1]))
  elseif l:start[1] == l:end[1]
    call add(l:pos, [l:start[1], l:start[2], l:end[2] - l:start[2] + 1])
  else
    call add(l:pos, [l:start[1], l:start[2], 999])
    call extend(l:pos, range(l:start[1] + 1, l:end[1] - 1))
    call add(l:pos, [l:end[1], 1, l:end[2]])
  endif
  let s:yank_hl_id = matchaddpos('IncSearch', l:pos, 100)
  call timer_start(200, function('s:yank_clear'))
endfunction
augroup highlight_yank
  autocmd!
  autocmd TextYankPost * silent! call s:highlight_yank()
augroup END

" Show cursorline only in the active window
augroup cursorline_active
  autocmd!
  autocmd WinEnter,FocusGained * setlocal cursorline
  autocmd WinLeave,FocusLost   * setlocal nocursorline
augroup END

" Trim trailing whitespace and empty lines on save
function! s:trim_trailing() abort
  if !&modifiable || line('$') > 10000
    return
  endif
  let l:save = winsaveview()
  if &filetype !=# 'markdown'
    silent! keeppatterns %s/\s\+$//e
  endif
  silent! keeppatterns %s/\($\n\s*\)\+\%$//e
  call winrestview(l:save)
endfunction
augroup trim_trailing
  autocmd!
  autocmd BufWritePre * call s:trim_trailing()
augroup END

" Drop expensive features for very large files
function! s:large_file_init() abort
  if getfsize(expand('%:p')) > 5 * 1024 * 1024
    let b:is_large_file = 1
    setlocal noswapfile noundofile nospell foldmethod=manual
  endif
endfunction
augroup large_file
  autocmd!
  autocmd BufReadPre * call s:large_file_init()
  autocmd BufReadPost * if exists('b:is_large_file') | setlocal syntax= | endif
augroup END

" ------------------------------------------------------------------------------
" Commands and functions
" ------------------------------------------------------------------------------

" Allow files to be saved as root when forgetting to start vim using sudo
command! W :execute ':silent! write !sudo tee %:S >/dev/null' | :edit!

" Yank absolute path of current buffer
command! Ypwd :let @+ = expand('%:p')

function! KillBufferOrCloseWindow()
  " Exit if in command window (access with q: or Q)
  if getcmdwintype() != ''
    quit
    return
  endif
  let l:curbuf = bufnr('%')
  " Handle multiple windows showing current buffer
  if len(win_findbuf(l:curbuf)) > 1
    close
    return
  endif
  " Check if there are other valid buffers
  let l:has_valid_buffer = 0
  for buf in getbufinfo()
    if buf.listed && buf.bufnr != l:curbuf
      let l:has_valid_buffer = 1
      break
    endif
  endfor
  let l:should_quit = !l:has_valid_buffer
  let l:ft = &filetype
  if l:ft ==# "netrw"
    bdelete
    return
  endif
  if &modified
    let l:choice = confirm("Buffer has unsaved changes. Save before closing?", "&Yes\n&No\n&Cancel", 1)
    if l:choice == 1
      let l:filename = ""
      if empty(bufname("%"))
        let l:filename = input("Enter file name to save: ")
        if empty(l:filename)
          return
        endif
      endif
      try
        execute 'write ' . fnameescape(l:filename)
      catch
        echoerr "Failed to save buffer: " . v:exception
        return
      endtry
    elseif l:choice == 2
      bdelete!
    else
      return
    endif
  else
    bdelete
  endif
  if l:should_quit
    quit
  endif
endfunction

function! Clearregs() abort
  let regs=split('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/-"', '\zs')
  for r in regs
    call setreg(r, @_)
  endfor
endfunction

" ------------------------------------------------------------------------------
" Color scheme
" ------------------------------------------------------------------------------

colorscheme tokyonight-storm

highlight clear SpellBad
highlight clear SpellCap
highlight clear SpellRare
highlight clear SpellLocal
highlight Normal       guibg=NONE
highlight NormalFloat  guibg=NONE
highlight SignColumn   guibg=NONE
highlight FoldColumn   guibg=NONE
highlight CursorLine   cterm=NONE      gui=NONE
highlight CursorLineNr cterm=NONE      gui=NONE
highlight SpellBad     cterm=underline gui=underline
highlight SpellCap     cterm=underline gui=underline
highlight SpellRare    cterm=underline gui=underline
highlight SpellLocal   cterm=underline gui=underline
