" ------------------------------------------------------------------------------
" Options
" ------------------------------------------------------------------------------

syntax on
filetype plugin indent on
set autoread
set hidden
set confirm
set number
set relativenumber
set numberwidth=2
set cursorline
" set autoindent " Minimal automatic indenting for any filetype
set backspace=indent,eol,start " Intuitive backspace behavior

set nolist
set listchars=space:·,tab:>-,trail:·,nbsp:+,eol:↵
set fillchars+=eob:\

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

set commentstring=#\ %s

set hlsearch
set incsearch
set ignorecase
set smartcase

set wrap
set whichwrap+=<,>,[,]
set virtualedit=block
set scrolloff=10
set sidescrolloff=8
set laststatus=2
set path+=**
set wildignorecase
set wildignore+=*/node_modules/*
set wildmenu
set wildmode=longest:full,full
set synmaxcol=400
set signcolumn=auto
set foldcolumn=1
set foldlevelstart=30

set smoothscroll
set splitkeep=screen
set jumpoptions=stack

set updatetime=5000
set updatecount=200
set ttimeoutlen=20
set timeoutlen=400

set linebreak
set breakindent
set mouse=a
set splitright splitbelow

" set lazyredraw
set termguicolors

set undodir=$XDG_DATA_HOME/vim/undo//
set undofile
set undolevels=1500

set viminfofile=$XDG_DATA_HOME/vim/viminfo

" % jumps across if/else/endif, HTML tags
packadd! matchit

let g:netrw_home = $XDG_DATA_HOME."/vim"
let g:quit_on_empty = !isdirectory(argv(0))

" Use a bar cursor in Insert mode, a block cursor in Normal mode, and an underline in Replace mode
" Reference chart of values:
"   Ps = 0  -> blinking block
"   Ps = 1  -> blinking block (default)
"   Ps = 2  -> steady block
"   Ps = 3  -> blinking underline
"   Ps = 4  -> steady underline
"   Ps = 5  -> blinking bar (xterm)
"   Ps = 6  -> steady bar (xterm)
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
let &t_SR = "\e[4 q"
let &t_ti .= "\e[2 q"
let &t_te .= "\e[0 q"

" Request focus reporting from the terminal so Vim can receives focus events
let &t_fe = "\e[?1004h"
let &t_fd = "\e[?1004l"

" ------------------------------------------------------------------------------
" Netrw
" ------------------------------------------------------------------------------

let g:netrw_banner=0
let g:netrw_altv=1
let g:netrw_list_hide = "^\./$"
let g:netrw_hide=1

" augroup netrw_mapping
"     autocmd!
"     autocmd filetype netrw nmap <buffer> <silent> H -
"     autocmd filetype netrw nmap <buffer> <silent> L <CR>
" augroup END

" ------------------------------------------------------------------------------
" Key mappings
" ------------------------------------------------------------------------------

let mapleader = " "

" <Esc> clears search highlight
nnoremap <silent> <Esc> :nohlsearch<CR>

" Move selected lines up/down (keeps selection)
vnoremap <silent> K :move '<-2<CR>gv=gv
vnoremap <silent> J :move '>+1<CR>gv=gv

" Keep cursor centered while scrolling/searching
nnoremap <silent> <C-d> <C-d>zz
nnoremap <silent> <C-u> <C-u>zz
nnoremap <silent> n nzzzv
nnoremap <silent> N Nzzzv

" Keep cursor in place while joining lines
nnoremap <silent> J mzJ`z

" Y behaves like C and D
nnoremap Y y$

" Paste over without losing the register
xnoremap p "_dP

" Delete to the black hole register (leader+d)
nnoremap <silent> <leader>d "_d
vnoremap <silent> <leader>d "_d

" System clipboard: <space>y/Y to copy, <space>p/P to paste
" (plain y/p use vim's internal registers)
nnoremap <silent> <leader>y "+y
vnoremap <silent> <leader>y "+y
nnoremap <silent> <leader>Y "+Y
vnoremap <silent> <leader>Y "+Y
nnoremap <silent> <leader>p "+p
vnoremap <silent> <leader>p "+p
nnoremap <silent> <leader>P "+P
vnoremap <silent> <leader>P "+P

" Alt+h/l buffer switching, Alt+j/k quickfix navigation
nnoremap <silent> <M-h> :bprevious<CR>
nnoremap <silent> <M-l> :bnext<CR>
nnoremap <silent> <M-j> :cnext<CR>
nnoremap <silent> <M-k> :cprev<CR>

" Replace word under cursor (Ctrl-S)
nnoremap <C-s> :%s/<C-r><C-w>/<C-r><C-w>/gIc<Left><Left><Left><Left>
vnoremap <C-s> :s///gIc<Left><Left><Left><Left><Left>

" Toggle invisible characters
nnoremap <silent> <leader>tl :set list!<CR>

" Make current file executable
nnoremap <silent> <leader>x :!chmod +x %<CR>

" Yank the whole file to the system clipboard
nnoremap <silent> <leader>[ :%yank +<CR>

" Disable arrow keys (forces hjkl navigation)
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
vnoremap <Up> <Nop>
vnoremap <Down> <Nop>
vnoremap <Left> <Nop>
vnoremap <Right> <Nop>

nnoremap <silent> Q :call SmartBufferClose()<CR>

" ------------------------------------------------------------------------------
" Commands
" ------------------------------------------------------------------------------

" Yank absolute path of current buffer
command! Ypwd :let @+ = expand('%:p')

command! W call SudoWrite()

command! Clearqf call setqflist([])

" ------------------------------------------------------------------------------
" Plugins
" ------------------------------------------------------------------------------

" fzf.vim: lazy-loaded via pack/*/opt
" Needs the main fzf repo's vim plugin also in opt/
let g:fzf_layout = {'window': {'width': 1.0, 'height': 1.0, 'yoffset': 0, 'xoffset': 0, 'border': 'none'}}
let g:fzf_vim = {'preview_window': ['up,60%,border-bottom', 'ctrl-/']}
let g:fzf_rg_options = ['--bind', 'ctrl-l:select-all+accept']

" Files: ctrl-l to put candidates into quickfix list
let g:fzf_files_options = ['--bind', 'ctrl-l:select-all+print(FZF-QF)+accept']

let $FZF_DEFAULT_COMMAND = 'fd --type f --hidden --exclude .git --exclude .venv --exclude node_modules'
let $FZF_DEFAULT_OPTS = '--layout=reverse'

autocmd VimEnter * packadd fzf
autocmd VimEnter * packadd fzf.vim
" Overrides :Files behaviour, re-define it to route through the custom sink
" (ctrl-l -> quickfix), keeping -bang and arbitrary args
autocmd VimEnter * command! -bang -nargs=* Files call s:fzf_files_qf(<q-args>, <bang>0)

" files in cwd
nnoremap <silent> <leader>fd :Files<CR>
" recent files
nnoremap <silent> <leader>fr :History<CR>
" opened buffers
nnoremap <silent> <leader>fo :Buffers<CR>
" marks
nnoremap <silent> <leader>fm :Marks<CR>
" current buffer fuzzy find
nnoremap <silent> <leader>ff :BLines<CR>
" live grep in cwd (RG = non-fuzzy, rg re-runs per keystroke)
nnoremap <silent> <leader>gd :RG<CR>
" grep word under cursor
nnoremap <silent> <leader>gw :RG <C-r><C-w><CR>
" git files
nnoremap <silent> <leader>fp :GFiles<CR>
" git commits
nnoremap <silent> <leader>gc :Commits<CR>
" git commits of file
nnoremap <silent> <leader>gf :BCommits<CR>
" git status
nnoremap <silent> <leader>gg :GFiles?<CR>
" quickfix list
nnoremap <silent> <leader>qf :call <SID>quickfix_fzf()<CR>

" help tags
nnoremap <silent> <leader>sh :Helptags<CR>

let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'PmenuMatch'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'PmenuMatchSel'],
  \ 'info':    ['fg', 'Comment'],
  \ 'border':  ['fg', 'FloatBorder'],
  \ 'prompt':  ['fg', 'PmenuMatch'],
  \ 'pointer': ['bg', 'Foo'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Comment'],
  \ 'header':  ['fg', 'Comment'],
  \ 'gutter':  ['bg', 'Normal'] }

" ------------------------------------------------------------------------------

" vim-fugitive: lazy-loaded via pack/*/opt
" Plugin loads on <leader>gs mapping or any of the G* user commands below
autocmd CmdUndefined Gsplit,Gdiffsplit,Gvdiffsplit,Gedit,Gread,Gwrite,Ggrep,GMove,GRename,GDelete,GRemove,GBrowse packadd fugitive

command! -bang -nargs=? G   packadd fugitive | G<bang> <args>
command! -bang -nargs=? Git packadd fugitive | Git<bang> <args>

nnoremap <silent> <leader>gs :Git<CR>

" ------------------------------------------------------------------------------

" vim-commentary: lazy-loaded via pack/*/opt
autocmd VimEnter * packadd vim-commentary

" ------------------------------------------------------------------------------
" Autocmds
" ------------------------------------------------------------------------------

augroup number_toggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

augroup text_filetype_specific_config
  autocmd!
  autocmd FileType text,markdown,org,gitcommit setlocal list
  autocmd FileType text,markdown,org,gitcommit setlocal listchars+=eol:↲
  autocmd FileType text,markdown,org,gitcommit setlocal spell
  autocmd FileType text,markdown,org,gitcommit setlocal spelllang=en_us,en_gb
augroup END

augroup code_filetype_specific_tab_config
  autocmd!
  autocmd FileType lua,yaml,json,vim setlocal tabstop=2 softtabstop=2 shiftwidth=2
augroup END

" Show cursorline only in the active window
augroup cursorline_active
  autocmd!
  autocmd WinEnter,FocusGained * setlocal cursorline
  autocmd WinLeave,FocusLost   * setlocal nocursorline
augroup END

" Trim trailing whitespace and empty lines on save
function! s:trim_trailing() abort
  if !&modifiable || line('$') > 10000
    return
  endif
  let l:save = winsaveview()
  if &filetype !=# 'markdown'
    silent! keeppatterns %s/\s\+$//e
  endif
  silent! keeppatterns %s/\($\n\s*\)\+\%$//e
  call winrestview(l:save)
endfunction
augroup trim_trailing
  autocmd!
  autocmd BufWritePre * call s:trim_trailing()
augroup END

" Drop expensive features for very large files
function! s:large_file_init() abort
  if getfsize(expand('%:p')) > 5 * 1024 * 1024
    let b:is_large_file = 1
    setlocal noswapfile noundofile nospell foldmethod=manual
  endif
endfunction
augroup large_file
  autocmd!
  autocmd BufReadPre * call s:large_file_init()
  autocmd BufReadPost * if exists('b:is_large_file') | setlocal syntax= | endif
augroup END

augroup highlight_yank
  autocmd!
  autocmd TextYankPost * silent! call s:highlight_yank()
augroup END

" ------------------------------------------------------------------------------
" Util functions
" ------------------------------------------------------------------------------

" fzf sink: ctrl-l in :Files sends all candidates to the quickfix
" select-all + a print marker lets the sink tell ctrl-l apart from Enter
function! s:fzf_files_sink(lines) abort
  if get(a:lines, 1, '') ==# 'FZF-QF'
    call setqflist(map(a:lines[2:], '{"filename": fnamemodify(v:val, ":p"), "lnum": 1, "text": ""}'))
    copen
    return
  endif
  let pkey = get(get(g:, 'fzf_vim', {}), 'paste_key', 'alt-enter')
  if get(a:lines, 0, '') ==# pkey
    return fzf#vim#paste(a:lines[1:])
  endif
  for f in a:lines[1:]
    execute 'edit' fnameescape(f)
  endfor
endfunction

function! s:fzf_files_qf(arg, bang) abort
  call fzf#vim#files(a:arg, extend(fzf#vim#with_preview(), {'sink*': function('s:fzf_files_sink')}), a:bang)
endfunction

" Focus quickfix window after ctrl-l
function! s:fzf_listproc_qf(list) abort
  call setqflist(a:list)
  copen
endfunction
let g:fzf_vim = extend(get(g:, 'fzf_vim', {}), {'listproc': function('s:fzf_listproc_qf')})

function! s:qf_sink(line)
  let parts = matchlist(a:line, '\v^(.{-}):(\d+):(.*)$')
  execute 'edit' fnameescape(parts[1])
  call cursor(parts[2], 0)
endfunction

" fzf browser over the current quickfix list
function! s:quickfix_fzf()
  let qf = getqflist()
  if empty(qf) | echo 'Quickfix is empty' | return | endif
  let source = map(qf, {_, e -> empty(bufname(e.bufnr)) ? e.filename : bufname(e.bufnr) . ':' . e.lnum . ':' . e.text})
  call fzf#run(fzf#wrap({'source': source, 'sink': function('s:qf_sink')}))
endfunction

" ------------------------------------------------------------------------------

let s:yank_hl_id = 0
function! s:yank_clear(...) abort
  if s:yank_hl_id
    silent! call matchdelete(s:yank_hl_id)
    let s:yank_hl_id = 0
  endif
endfunction

" Highlight the region just yanked/deleted (fades out)
function! s:highlight_yank() abort
  if v:event.operator !~# '^[yd]$'
    return
  endif
  call s:yank_clear()
  let l:start = getpos("'[")
  let l:end = getpos("']")
  let l:pos = []
  if v:event.regtype ==# 'V'
    call extend(l:pos, range(l:start[1], l:end[1]))
  elseif l:start[1] == l:end[1]
    call add(l:pos, [l:start[1], l:start[2], l:end[2] - l:start[2] + 1])
  else
    call add(l:pos, [l:start[1], l:start[2], 999])
    call extend(l:pos, range(l:start[1] + 1, l:end[1] - 1))
    call add(l:pos, [l:end[1], 1, l:end[2]])
  endif
  let s:yank_hl_id = matchaddpos('IncSearch', l:pos, 100)
  call timer_start(200, function('s:yank_clear'))
endfunction

function! s:PromptFilename() abort
  let l:filepath = input('Enter filename: ', getcwd() . '/', 'file')
  return empty(l:filepath) ? '' : fnamemodify(l:filepath, ':p')
endfunction

" Allow files to be saved as root when forgetting to start vim using sudo
function! SudoWrite() abort
  let l:filepath = expand('%:p')
  let l:unnamed = empty(l:filepath)
  if l:unnamed
    let l:filepath = s:PromptFilename()
    if empty(l:filepath)
      return
    endif
    if bufnr(l:filepath) != -1
      echoerr 'E95: Buffer with this name already exists'
      return
    endif
  endif

  silent execute 'write !sudo tee ' . shellescape(l:filepath) . ' >/dev/null'
  if v:shell_error != 0
    echoerr 'sudo write failed'
    return
  endif
  if l:unnamed
    execute 'file ' . fnameescape(l:filepath)
  endif
  edit!
endfunction

function! Clearregs() abort
  let regs=split('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/-"', '\zs')
  for r in regs
    call setreg(r, @_)
  endfor
endfunction

function! s:IsNormalBuffer(bufnr) abort
  let l:buftype = getbufvar(a:bufnr, '&buftype')
  return buflisted(a:bufnr) && (l:buftype ==# 'terminal'
     \ || (empty(l:buftype) && getbufvar(a:bufnr, '&filetype') !=# 'netrw'))
endfunction

function! s:CloseCurrentWindow() abort
  execute winnr('$') == 1 && tabpagenr('$') > 1 ? 'tabclose!' : 'close!'
endfunction

function! s:SelectBufferToSwitch(buffers) abort
  let l:hidden = {'bufnr': -1, 'lastused': -1}
  let l:any = {'bufnr': -1, 'lastused': -1}
  for l:buffer in a:buffers
    if l:buffer.lastused > l:any.lastused
      let l:any = l:buffer
    endif
    if empty(l:buffer.windows) && l:buffer.lastused > l:hidden.lastused
      let l:hidden = l:buffer
    endif
  endfor
  return l:hidden.bufnr != -1 ? l:hidden.bufnr : l:any.bufnr
endfunction

function! s:ConsolidateWindows(valid_buffer_count) abort
  let l:current_win = win_getid()
  let l:primary = {}
  let l:duplicates = []
  let l:normal_win_count = 0

  for l:window in getwininfo()
    if get(l:window, 'popup', 0) || !s:IsNormalBuffer(l:window.bufnr)
      continue
    endif
    let l:normal_win_count += 1
    let l:key = string(l:window.bufnr)
    if !has_key(l:primary, l:key)
      let l:primary[l:key] = l:window.winid
    elseif l:primary[l:key] == l:current_win
      call add(l:duplicates, l:window.winid)
    elseif l:window.winid == l:current_win
      call add(l:duplicates, l:primary[l:key])
      let l:primary[l:key] = l:current_win
    else
      call add(l:duplicates, l:window.winid)
    endif
  endfor

  if l:normal_win_count <= a:valid_buffer_count
    return
  endif
  for l:winid in reverse(l:duplicates)
    if win_id2tabwin(l:winid)[0] != 0
      call win_execute(l:winid, 'close!')
    endif
  endfor
endfunction

" Universal buffer close:
" - Prompts to save modified and unnamed buffers
" - Handles special buffers, terminals, and netrw duplicates
" - Preserves window layouts and optionally quits when empty
function! SmartBufferClose() abort
  if getcmdwintype() !=# ''
    quit
    return
  endif

  let l:current = bufnr('%')
  let l:current_windows = win_findbuf(l:current)
  let l:force = 0
  let l:destructive_hide = index(['delete', 'unload', 'wipe'], &bufhidden) != -1
  let l:window_count = len(filter(getwininfo(), '!get(v:val, "popup", 0)'))
  if !s:IsNormalBuffer(l:current) && &buftype !=# 'terminal' && l:window_count > 1
     \ && (!&modified || !l:destructive_hide)
    call s:CloseCurrentWindow()
    return
  endif

  if &filetype ==# 'netrw' && exists('b:netrw_curdir')
    let l:netrw_dir = simplify(fnamemodify(b:netrw_curdir, ':p'))
    for l:buffer in getbufinfo({'buflisted': 1})
      if l:buffer.bufnr != l:current && empty(win_findbuf(l:buffer.bufnr))
         \ && !l:buffer.changed && getbufvar(l:buffer.bufnr, '&filetype') ==# 'netrw'
         \ && !empty(l:buffer.name) && isdirectory(l:buffer.name)
         \ && simplify(fnamemodify(l:buffer.name, ':p')) ==# l:netrw_dir
        execute 'silent! bdelete! ' . l:buffer.bufnr
        break
      endif
    endfor
  endif

  let l:remaining = []
  for l:buffer in getbufinfo({'buflisted': 1})
    if l:buffer.bufnr != l:current && s:IsNormalBuffer(l:buffer.bufnr)
      call add(l:remaining, l:buffer)
    endif
  endfor

  if empty(l:remaining) && len(l:current_windows) > 1 && &buftype !=# 'terminal'
    call s:CloseCurrentWindow()
    return
  endif

  if &modified && &buftype !=# 'terminal'
    let l:choice = confirm('Save before closing the buffer?', "&Yes\n&No\n&Cancel", 1)
    if l:choice == 1
      let l:filepath = empty(bufname('%')) ? s:PromptFilename() : ''
      if empty(bufname('%')) && empty(l:filepath)
        return
      endif
      try
        execute 'write ' . fnameescape(l:filepath)
      catch
        echoerr 'Failed to save buffer: ' . v:exception
        return
      endtry
    elseif l:choice == 2
      let l:force = 1
    else
      return
    endif
  endif

  if &buftype ==# 'terminal' && !l:force && exists('*term_getjob')
     \ && job_status(term_getjob(l:current)) ==# 'run'
    if confirm('Terminal has a running job.', "&Ignore\n&Cancel", 1) != 1
      return
    endif
    let l:force = 1
  endif

  if empty(l:remaining) && len(l:current_windows) > 1
    call s:CloseCurrentWindow()
    return
  endif

  if empty(l:remaining)
    if get(g:, 'quit_on_empty', 1) && !l:force
      try
        quitall
      catch
        echoerr 'Failed to quit: ' . v:exception
      endtry
      return
    endif
    try
      execute 'bdelete' . (l:force ? '!' : '') . ' ' . l:current
    catch
      echoerr 'Failed to close buffer: ' . v:exception
      return
    endtry
    if get(g:, 'quit_on_empty', 1)
      try
        quitall
      catch
        echoerr 'Failed to quit: ' . v:exception
      endtry
    endif
    return
  endif

  let l:switch_to = s:SelectBufferToSwitch(l:remaining)
  try
    for l:winid in l:current_windows
      call win_execute(l:winid, 'buffer' . (l:force ? '!' : '') . ' ' . l:switch_to)
    endfor
    if buflisted(l:current) || bufloaded(l:current)
      execute 'bdelete' . (l:force ? '!' : '') . ' ' . l:current
    endif
  catch
    echoerr 'Failed to close buffer: ' . v:exception
    return
  endtry
  call s:ConsolidateWindows(len(l:remaining))
endfunction

" ------------------------------------------------------------------------------
" Color scheme
" ------------------------------------------------------------------------------

colorscheme tokyonight-storm

highlight clear SpellBad
highlight clear SpellCap
highlight clear SpellRare
highlight clear SpellLocal
highlight Normal       guibg=NONE
highlight NormalFloat  guibg=NONE
highlight SignColumn   guibg=NONE
highlight FoldColumn   guibg=NONE
highlight CursorLine   cterm=NONE      gui=NONE
highlight CursorLineNr cterm=NONE      gui=NONE
highlight SpellBad     cterm=underline gui=underline
highlight SpellCap     cterm=underline gui=underline
highlight SpellRare    cterm=underline gui=underline
highlight SpellLocal   cterm=underline gui=underline
" vim's `:highlight` only overrides the keys configured, and keeps leftover defaults:
" - Visual default carries guifg=Black, which would render black on the dark bg
" - IncSearch default carries gui=reverse, which inverts fg/bg
highlight Visual       guifg=NONE
highlight IncSearch    gui=NONE   cterm=NONE
