numbered_command = false

mouse_support = true
focus_on_create = true
use_trash = true
watch_files = true
xdg_open = true
xdg_open_fork = true
case_insensitive_ext = false
zoxide_update = false

custom_commands = []

[display]
# default, minimal, hsplit
mode = "default"

automatically_count_files = true
collapse_preview = true
# ratios for parent view (optional), current view and preview
column_ratio = [1, 3, 4]
scroll_offset = 6
show_borders = true
show_hidden = true
show_icons = true
# none, absolute, relative
line_number_style = "relative"

# size, mtime, user, gourp, perm. can be combined with |.
# `none` to disable, `all` to enable all
# all and none can't be combined with other options
linemode = "size | mtime"

[display.sort]
# lexical, mtime, natural, size, ext
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 2097152                           # 2MB
preview_script = "~/.config/joshuto/preview_file.sh" # make sure it's marked as executable
use_xdg_thumbs = true
# preview_protocol = "kitty"
# xdg_thumb_size = "xxlarge"

[search]
# insensitive, sensitive, smart
string_case_sensitivity = "insensitive"
# see above
glob_case_sensitivity = "sensitive"
# see above
regex_case_sensitivity = "sensitive"
# see above
fzf_case_sensitivity = "insensitive"

[cmd_aliases]
q = "quit"

[tab]
# inherit, home, root
home_page = "home"
