[general]
fullscreen = true
early-exit = true
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 2
output-filename = "/home/domenic/Pictures/screenshots/%Y-%m-%d_%H:%M:%S.png"
save-after-copy = true
default-hide-toolbars = false
primary-highlighter = "block"
disable-notifications = false

[font]
family = "Roboto"
style = "Bold"
